
package org.kth.webservice.flight;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://Flight.webservice.kth.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Flight.webservice.kth.org/HelloWorld/getHelloWorldAsStringRequest", output = "http://Flight.webservice.kth.org/HelloWorld/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login")
    @WebResult(partName = "return")
    @Action(input = "http://Flight.webservice.kth.org/HelloWorld/LoginRequest", output = "http://Flight.webservice.kth.org/HelloWorld/LoginResponse")
    public String login(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

}
